import { useState } from 'react'
import { estimateEnergy, macroCalories, number } from '../lib/nutrition.js'

const activity = [['1.2', 'Sedentario'], ['1.375', 'Ligera'], ['1.55', 'Moderada'], ['1.725', 'Alta'], ['1.9', 'Muy alta']]
export default function Profile({ profile, onSave, onLogout, pending }) {
  const [draft, setDraft] = useState(profile); const [message, setMessage] = useState('')
  const set = (key, value) => setDraft(previous => ({ ...previous, [key]: number(value) }))
  const kcal = macroCalories(draft); const estimate = draft.weight && draft.height && draft.age && draft.sex ? estimateEnergy(draft) : null
  const submit = async e => { e.preventDefault(); try { await onSave(draft); setMessage('Perfil guardado.') } catch (error) { setMessage(error.message) } }
  return <main><div className="page-heading"><div><p className="eyebrow">AJUSTES</p><h1>Tu perfil</h1></div>{pending > 0 && <span className="pending-pill">{pending} pendiente{pending > 1 ? 's' : ''}</span>}</div><form className="form profile-form" onSubmit={submit}><section><h2>Objetivo diario</h2><p className="muted">Las calorías se calculan a partir de tus macros.</p><div className="kcal-result"><strong>{kcal} kcal</strong><span>4 kcal/g carbohidratos · 4 proteínas · 9 grasas</span></div><div className="macro-inputs">{[['carbs', 'Carbohidratos'], ['protein', 'Proteínas'], ['fat', 'Grasas']].map(([key, label]) => <label key={key}>{label}<input type="number" min="0" value={draft[key] ?? 0} onChange={e => set(key, e.target.value)} /><small>gramos</small></label>)}</div></section><section><h2>Estimación energética</h2><p className="muted">Opcional. Ecuación de Mifflin-St Jeor (1990); no modifica tu objetivo.</p><div className="two-col"><label>Peso (kg)<input type="number" min="1" value={draft.weight ?? ''} onChange={e => set('weight', e.target.value)} /></label><label>Altura (cm)<input type="number" min="1" value={draft.height ?? ''} onChange={e => set('height', e.target.value)} /></label><label>Edad<input type="number" min="1" value={draft.age ?? ''} onChange={e => set('age', e.target.value)} /></label><label>Sexo<select value={draft.sex || 'male'} onChange={e => setDraft(p => ({ ...p, sex: e.target.value }))}><option value="male">Hombre</option><option value="female">Mujer</option></select></label></div><label>Actividad<select value={draft.activity || 1.2} onChange={e => set('activity', e.target.value)}>{activity.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label>{estimate && <div className="estimate"><span>Basal <b>{estimate.resting} kcal</b></span><span>Factor <b>×{draft.activity}</b></span><span>Mantenimiento <b>{estimate.maintenance} kcal</b></span></div>}</section><button type="submit">Guardar perfil</button>{message && <p className={message === 'Perfil guardado.' ? 'success' : 'error'}>{message}</p>}</form><button className="link-button" onClick={onLogout}>Cerrar sesión</button></main>
}
