import { useMemo, useState } from 'react'
import { scaleNutrients, sumNutrients, macroCalories, nutrientText } from '../lib/nutrition.js'
import DateControl from '../components/DateControl.jsx'
import Scanner from '../components/Scanner.jsx'
import { api } from '../lib/api.js'

const meals = ['Desayuno', 'Comida', 'Cena', 'Snacks']
export default function Today({ date, setDate, entries, profile, foods, onAdd, onEdit, onDelete, onCopy }) {
  const [meal, setMeal] = useState('Desayuno'); const [foodId, setFoodId] = useState(''); const [quantity, setQuantity] = useState(100); const [scanner, setScanner] = useState(false)
  const totals = useMemo(() => sumNutrients(entries.map(entry => scaleNutrients(entry.food.nutrients, entry.quantity))), [entries])
  const goal = { kcal: macroCalories(profile), carbs: profile.carbs || 0, protein: profile.protein || 0, fat: profile.fat || 0 }
  const add = e => { e.preventDefault(); const food = foods.find(item => item.id === foodId); if (food && quantity > 0) { onAdd({ id: crypto.randomUUID(), date, meal, food, quantity: Number(quantity) }); setFoodId('') } }
  const scan = async barcode => { setScanner(false); try { const food = await api(`/api/lookup/${encodeURIComponent(barcode)}`); onAdd({ id: crypto.randomUUID(), date, meal, food, quantity: Number(quantity) }) } catch {} }
  return <main><div className="page-heading"><div><p className="eyebrow">DIARIO</p><h1>Hoy, a tu ritmo</h1></div><button className="secondary" onClick={onCopy}>Copiar ayer</button></div><DateControl date={date} onChange={setDate} /><section className="hero-card"><div><span className="muted">Energía</span><strong>{nutrientText(totals.kcal)} <small>/ {nutrientText(goal.kcal)} kcal</small></strong><div className="progress"><i style={{ width: `${totals.kcal == null ? 0 : Math.min(100, goal.kcal ? totals.kcal / goal.kcal * 100 : 0)}%` }} /></div></div><div className="macro-grid">{[['C', totals.carbs, goal.carbs], ['P', totals.protein, goal.protein], ['G', totals.fat, goal.fat]].map(([label, value, target]) => <div key={label}><b>{label}</b><span>{nutrientText(value)}<small>/{nutrientText(target)}g</small></span></div>)}</div></section><form className="quick-add" onSubmit={add}><select value={meal} onChange={e => setMeal(e.target.value)}>{meals.map(item => <option key={item}>{item}</option>)}</select><select aria-label="Alimento" value={foodId} onChange={e => setFoodId(e.target.value)}><option value="">Añade un alimento…</option>{foods.map(food => <option key={food.id} value={food.id}>{food.name}{food.brand ? ` · ${food.brand}` : ''}</option>)}</select><input aria-label="Cantidad" type="number" min="1" value={quantity} onChange={e => setQuantity(e.target.value)} /><span>{foods.find(item => item.id === foodId)?.basis || 'g'}</span><button disabled={!foodId}>Añadir</button><button type="button" className="secondary" onClick={() => setScanner(true)}>Escanear</button></form><div className="meals">{meals.map(name => <section className="meal" key={name}><h2>{name}<span>{nutrientText(sumNutrients(entries.filter(e => e.meal === name).map(e => scaleNutrients(e.food.nutrients, e.quantity))).kcal)} kcal</span></h2>{entries.filter(entry => entry.meal === name).map(entry => <article className={`entry ${entry.pending ? 'pending' : ''}`} key={entry.id}><button className="entry-main" onClick={() => onEdit(entry)}><strong>{entry.food.name}</strong><span>{entry.quantity} {entry.food.basis} · {nutrientText(scaleNutrients(entry.food.nutrients, entry.quantity).kcal)} kcal {entry.pending && ' · pendiente'}</span></button><button className="delete" onClick={() => onDelete(entry)} aria-label={`Eliminar ${entry.food.name}`}>×</button></article>)}{!entries.some(entry => entry.meal === name) && <p className="empty">Aún no has añadido nada.</p>}</section>)}</div>{scanner && <Scanner onResult={scan} onClose={() => setScanner(false)} />}</main>
}
