import { useMemo, useState } from 'react'
import { scaleNutrients, sumNutrients } from '../lib/nutrition.js'

export default function RecipeBuilder({ foods, onSave, onCancel }) {
  const [name, setName] = useState(''); const [yieldGrams, setYieldGrams] = useState(''); const [parts, setParts] = useState([]); const [foodId, setFoodId] = useState(''); const [quantity, setQuantity] = useState('100')
  const totals = useMemo(() => sumNutrients(parts.map(part => scaleNutrients(part.food.nutrients, part.quantity))), [parts])
  const per100 = useMemo(() => Object.fromEntries(Object.entries(totals).map(([key, value]) => [key, value == null || !Number(yieldGrams) ? null : value * 100 / Number(yieldGrams)])), [totals, yieldGrams])
  const addPart = () => { const food = foods.find(item => item.id === foodId); if (food && Number(quantity) > 0) { setParts(current => [...current, { food, quantity: Number(quantity) }]); setFoodId('') } }
  const save = e => { e.preventDefault(); if (!name.trim() || !Number(yieldGrams) || !parts.length) return; onSave({ id: crypto.randomUUID(), name: name.trim(), brand: '', barcode: '', basis: 'g', nutrients: per100, servingSize: 100, recipe: { yieldGrams: Number(yieldGrams), ingredients: parts.map(part => ({ foodId: part.food.id, quantity: part.quantity })) } }) }
  return <form className="form" onSubmit={save}><p className="muted">Las cantidades de ingredientes se convierten a valores por 100 g del plato terminado.</p><label>Nombre de la receta<input required value={name} onChange={e => setName(e.target.value)} placeholder="Ej. Lentejas caseras" /></label><label>Rendimiento final (g)<input required type="number" min="1" value={yieldGrams} onChange={e => setYieldGrams(e.target.value)} /></label><div className="recipe-add"><select value={foodId} onChange={e => setFoodId(e.target.value)}><option value="">Ingrediente…</option>{foods.map(food => <option key={food.id} value={food.id}>{food.name}</option>)}</select><input type="number" min="1" value={quantity} onChange={e => setQuantity(e.target.value)} /><button type="button" onClick={addPart}>Añadir</button></div>{parts.map((part, index) => <div className="recipe-part" key={`${part.food.id}-${index}`}><span>{part.food.name} · {part.quantity} g</span><button type="button" className="delete" onClick={() => setParts(current => current.filter((_, i) => i !== index))}>×</button></div>)}<div className="recipe-total"><span>Por 100 g</span><b>{Object.entries(per100).map(([key, value]) => `${key === 'kcal' ? '' : key[0].toUpperCase()}${value == null ? '—' : Math.round(value)}${key === 'kcal' ? ' kcal' : 'g'}`).join(' · ')}</b></div><footer className="form-actions"><button type="button" className="secondary" onClick={onCancel}>Cancelar</button><button disabled={!parts.length}>Guardar receta</button></footer></form>
}
