import {chromium} from '@playwright/test';
import assert from 'node:assert/strict';
const base=process.env.PREVIEW_URL||'http://127.0.0.1:3101';
const browser=await chromium.launch({headless:true});
const context=await browser.newContext({viewport:{width:390,height:844},timezoneId:'Europe/Madrid'});
const page=await context.newPage(); const errors=[];page.on('pageerror',error=>errors.push(error.message));
try {
  await page.goto(base); await page.getByRole('button',{name:/Perfil/}).waitFor(); await page.getByRole('button',{name:/Perfil/}).click();
  await page.getByLabel('Carbohidratos',{exact:false}).fill('250');
  await page.getByLabel('Proteínas',{exact:false}).fill('150');
  await page.getByLabel('Grasas',{exact:false}).fill('70');
  assert.match(await page.locator('.kcal-result').innerText(),/2230/);
  await page.getByRole('button',{name:'Guardar perfil',exact:true}).click();
  await page.getByText('Perfil guardado.',{exact:true}).waitFor();
  await page.getByRole('button',{name:/Alimentos/}).click();
  await page.getByRole('button',{name:'+ Nuevo',exact:true}).click();
  const form=page.getByRole('dialog');await form.getByLabel('Nombre',{exact:true}).fill('Avena prueba UI');
  await form.getByLabel('kcal',{exact:true}).fill('380');await form.getByLabel('Carbohidratos',{exact:true}).fill('60');
  await form.getByLabel('Proteínas',{exact:true}).fill('12');await form.getByLabel('Grasas',{exact:true}).fill('8');
  await form.getByRole('button',{name:'Guardar alimento',exact:true}).click();await form.waitFor({state:'hidden'});
  await page.getByRole('button',{name:/Hoy/}).click();
  await page.getByLabel('Fecha',{exact:true}).fill('2025-06-12');
  await page.waitForTimeout(150);
  await page.getByLabel('Alimento',{exact:true}).selectOption({label:'Avena prueba UI'});
  await page.getByLabel('Cantidad',{exact:true}).fill('75');
  await page.locator('form.quick-add').getByRole('button',{name:'Añadir',exact:true}).click();
  await page.locator('.entry').filter({hasText:'Avena prueba UI'}).waitFor();
  await page.reload(); await page.getByLabel('Fecha',{exact:true}).fill('2025-06-12'); await page.waitForTimeout(150);
  await page.locator('.entry').filter({hasText:'Avena prueba UI'}).waitFor();
  assert.match(await page.locator('.hero-card').innerText(),/285/);
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'mobile viewport overflow');
  await page.screenshot({path:'test-results/mobile-diary.png',fullPage:true});
  await page.setViewportSize({width:1280,height:900});await page.screenshot({path:'test-results/desktop-diary.png',fullPage:true});
  assert.deepEqual(errors,[]);console.log('UI PASS: profile grams, save food, historical date, persisted totals, mobile layout, no JS errors.');
} finally {await browser.close();}
